# Generated by Django 4.2.3 on 2023-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('service', models.CharField(choices=[('Websites', 'Websites'), ('Branding', 'Branding'), ('Ecommerce', 'Ecommerce'), ('SEO', 'SEO')], max_length=100)),
            ],
        ),
    ]
