# Generated by Django 4.2.3 on 2023-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(choices=[(1, 'React'), (2, 'Javascript'), (3, 'Android'), (4, 'Django'), (5, 'Bootstrap-5'), (6, 'Custom-CSS'), (7, 'Jquery'), (8, 'Node')], max_length=20),
        ),
    ]
