# Generated by Django 4.2.3 on 2023-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_technologies_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.TextField(max_length=200),
        ),
    ]
