# Generated by Django 4.2.3 on 2023-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[(1, 'Latest'), (2, 'New'), (3, 'Old')], max_length=100, null=True),
        ),
    ]
