# Generated by Django 4.2.3 on 2023-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Latest', 'Latest'), ('New', 'New'), ('Old', 'Old')], default='Latest', max_length=100),
        ),
    ]
