# Generated by Django 4.2.3 on 2023-09-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_profile_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
